// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CalendarCard: typeof import('./../components/CalendarCard.vue')['default']
    Drawer: typeof import('./../base/Drawer.vue')['default']
    Driver: typeof import('./../components/Driver/index.vue')['default']
    EchartsIncomeChart: typeof import('./../components/echarts/IncomeChart.vue')['default']
    EchartsOutpatientChart: typeof import('./../components/echarts/outpatientChart.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Fullscreen: typeof import('./../base/Fullscreen.vue')['default']
    Icon: typeof import('./../base/Icon.vue')['default']
    IncomeCard: typeof import('./../components/IncomeCard.vue')['default']
    Lang: typeof import('./../base/Lang.vue')['default']
    Message: typeof import('./../components/Message.vue')['default']
    NoticeCard: typeof import('./../components/NoticeCard.vue')['default']
    NoticeLink: typeof import('./../components/NoticeLink.vue')['default']
    OutpatientCard: typeof import('./../components/OutpatientCard.vue')['default']
    Pagination: typeof import('./../base/Pagination.vue')['default']
    Routes: typeof import('./../base/Routes.vue')['default']
    Title: typeof import('./../base/Title.vue')['default']
    UserAvatar: typeof import('./../base/UserAvatar.vue')['default']
    WangEditor: typeof import('./../components/WangEditor.vue')['default']
  }
}

export {}
