// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CalendarCard: typeof import('./../components/CalendarCard.vue')['default']
    Drawer: typeof import('./../base/Drawer.vue')['default']
    Driver: typeof import('./../components/Driver/index.vue')['default']
    EchartsIncomeChart: typeof import('./../components/echarts/IncomeChart.vue')['default']
    EchartsOutpatientChart: typeof import('./../components/echarts/outpatientChart.vue')['default']
    Fullscreen: typeof import('./../base/Fullscreen.vue')['default']
    Icon: typeof import('./../base/Icon.vue')['default']
    IncomeCard: typeof import('./../components/IncomeCard.vue')['default']
    Lang: typeof import('./../base/Lang.vue')['default']
    Message: typeof import('./../components/Message.vue')['default']
    NoticeCard: typeof import('./../components/NoticeCard.vue')['default']
    NoticeLink: typeof import('./../components/NoticeLink.vue')['default']
    OutpatientCard: typeof import('./../components/OutpatientCard.vue')['default']
    Pagination: typeof import('./../base/Pagination.vue')['default']
    Routes: typeof import('./../base/Routes.vue')['default']
    Title: typeof import('./../base/Title.vue')['default']
    UserAvatar: typeof import('./../base/UserAvatar.vue')['default']
    WangEditor: typeof import('./../components/WangEditor.vue')['default']
  }
}

export {}
